from enum import Enum

class PlazoPago(Enum):
    MENSUAL = "MENSUAL"
    TRIMESTRAL = "TRIMESTRAL"
    SEMESTRAL = "SEMESTRAL"
    ANUAL = "ANUAL"
    CUATRIMESTRAL = "CUATRIMESTRAL"
    BIMESTRAL = "BIMESTRAL"
