from enum import Enum

class TipoCondicion(Enum):
    RESPONSABLE_INSCRIPTO = "RESPONSABLE_INSCRIPTO"
    RESPONSABLE_NO_INSCRIPTO_O_EXENTO = "RESPONSABLE_NO_INSCRIPTO_O_EXENTO"
    MONOTRIBUTISTA = "MONOTRIBUTISTA"