from enum import Enum

class TipoCondicion(Enum):
    RESPONSABLE_INSCRIPTO = "RESPONSABLE_INSCRIPTO"
    RESPONSABLE_NO_INSCRIPTO = "RESPONSABLE_NO_INSCRIPTO"
    MONOTRIBUTISTA = "MONOTRIBUTISTA"
    RESPONSABLE_EXENTO_NO_ALCANZADO = "RESPONSABLE_EXENTO_NO_ALCANZADO"
